{ created_at: 'Tue Oct 11 12:16:59 +0000 2016',
   id: 785816465962364900,
   id_str: '785816465962364928',
   text: '#cricket Adam Hose: Somerset batsman extends contract for 2017 https://t.co/xZuDRxXzIR',
   source: '<a href="http://www.hootsuite.com" rel="nofollow">Hootsuite</a>',
   truncated: false,
   in_reply_to_status_id: null,
   in_reply_to_status_id_str: null,
   in_reply_to_user_id: null,
   in_reply_to_user_id_str: null,
   in_reply_to_screen_name: null,
   user:
    { id: 1695473731,
      id_str: '1695473731',
      name: 'XTN Cricket News',
      screen_name: 'xtcricket',
      location: 'Worldwide',
      url: 'http://www.xtremetweet.com',
      description: 'Tweeing #CricketNews & #Cricket Scores for around the globe.',
      protected: false,
      verified: false,
      followers_count: 204,
      friends_count: 86,
      listed_count: 9,
      favourites_count: 0,
      statuses_count: 10035,
      created_at: 'Sat Aug 24 03:39:06 +0000 2013',
      utc_offset: -14400,
      time_zone: 'Eastern Time (US & Canada)',
      geo_enabled: false,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: 'C0DEED',
      profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_link_color: '0084B4',
      profile_sidebar_border_color: 'C0DEED',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      profile_image_url: 'http://pbs.twimg.com/profile_images/378800000365112585/6a676aa242263c32b150c3f1f0a46390_normal.jpeg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/378800000365112585/6a676aa242263c32b150c3f1f0a46390_normal.jpeg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/1695473731/1404757892',
      default_profile: true,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null },
   geo: null,
   coordinates: null,
   place: null,
   contributors: null,
   is_quote_status: false,
   retweet_count: 0,
   favorite_count: 0,
   entities:
    { hashtags: [ [Object] ],
      urls: [ [Object] ],
      user_mentions: [],
      symbols: [] },
   favorited: false,
   retweeted: false,
   possibly_sensitive: false,
   filter_level: 'low',
   lang: 'en',
   timestamp_ms: '1476188219906' }
